# Use an official Node.js runtime as a parent image
FROM node:18 as build-stage

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to the container
COPY package*.json ./

# Install Nuxt.js dependencies
RUN yarn install

# Copy the rest of the application files to the container
COPY . .

# Build the Nuxt.js application
RUN yarn run build

# Copy the custom Nginx configuration
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Use an official Nginx image as a parent image for the production stage
FROM nginx:alpine

# Copy the built Nuxt.js application from the build-stage
COPY --from=build-stage /book-lib-fe/dist /usr/share/nginx/html

# Expose port 80 for Nginx
EXPOSE 80

# Start Nginx when the container runs
CMD ["nginx", "-g", "daemon off;"]
