# Docker-Compose Development Enviornment
version: '3'
services:
  fe-development:
    container_name: fe-development
    image: fe-development
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '80:80'
    expose:
      - 80
networks:
  default:
    name: Dev
